overblog_graphql:
    definitions:
        schema:
            mutation: Mutation
            query: Query
        mappings:
            types:
                -
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null