security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email   # ← this is correct for login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/               # protects your root endpoint
            stateless: true
            jwt: ~
            provider: app_user_provider   # ←←← ADD THIS LINE !!!

    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS }